services:
  # The Bridgeport Connecticut Proxy
  connecticut:
    image: us.gcr.io/computing-with-integrity/connecticut
    ports:
      - "3103:3103"
    environment:
      HTTP_PORT: 3103
      PORT: 3103

  # MongoDB
  bridgeport-mongo:
    image: mongo
    command: |
      bash -c "mongod --bind_ip_all --replSet rs0 --fork --syslog --port 3113 && mongo --port 3113 --eval \"if (!rs.status().ok) rs.initiate({_id : 'rs0', members : [{_id : 0, host : 'bridgeport-mongo:3113'}]})\" && mongo --port 3113 --eval \"while(true) {if (!rs.status().ok) break;sleep(1000)};\""
    hostname: "bridgeport-mongo"
    ports:
      - 3113:27017
    volumes:
     - ./data/bridgeport-mongo-data:/data/db

  bitquery-mongo-reader:
    hostname: "reader-1h48c3wg1ycgpt7tx61phzh8lx6v5tvukl"
    build: .
    # This environment is an example, specific to the UMP bridge.
    # It can be modified to work as the reader for any other compatible bridge.
    environment:
      BRIDGE: 'eyJpZCI6IjFINDhDM3dnMVljZ3BUN1R4NjFQSHpIOEx4NnY1dFZVS0wifQ=='
      PORT: 80
      MONGODB_READ_CREDS: 'bW9uZ29kYjovL2JyaWRnZXBvcnQtbW9uZ286MzExMy9icmlkZ2VfMUg0OEMzd2cxWWNncFQ3VHg2MVBIekg4THg2djV0VlVLTA=='
      MONGODB_DATABASE: 'bridge_1H48C3wg1YcgpT7Tx61PHzH8Lx6v5tVUKL'
      DEFAULT_QUERY: '{"v": 3,"q": {"collection": "users", "find": {}}}'
      DEFAULT_SOCKET: '{"v": 3,"q": {"find": {}}}'
    volumes:
      - ./exampleDocVolume:/app/doc
