services:
  bitquery-mongo-reader:
    build: .
    hostname: "reader-1h48c3wg1ycgpt7tx61phzh8lx6v5tvukl"
    container_name: "bitquery-mongo-reader"
    volumes:
      - ./src:/app/src
    environment:
      BRIDGE: 'eyJpZCI6IjFINDhDM3dnMVljZ3BUN1R4NjFQSHpIOEx4NnY1dFZVS0wifQ=='
      PORT: 80
      MONGODB_READ_CREDS: 'bW9uZ29kYjovL2JyaWRnZXBvcnQtbW9uZ286MzExMy9icmlkZ2VfMUg0OEMzd2cxWWNncFQ3VHg2MVBIekg4THg2djV0VlVLTA=='
      MONGODB_DATABASE: 'bridge_1H48C3wg1YcgpT7Tx61PHzH8Lx6v5tVUKL'

